### ISSUE TITLE
CRITICAL: Only works when npm linked

### ISSUE THREAD

**Issue by ianwremmel** [ianwremmel/koolaid#18]
When installed as a dependency, produces the following output:

```
/Users/ian/projects/nvironment/nvironment-api/node_modules/@ianwremmel/koolaid/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import {default as access} from './decorators/access';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ian/projects/nvironment/nvironment-api/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.cls_wrapMethod [as _load] (/Users/ian/projects/nvironment/nvironment-api/node_modules/newrelic/lib/shimmer.js:230:38)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ian/projects/nvironment/nvironment-api/src/server.js:4:29)
Warning: Command failed: /bin/sh -c node src/index.js
/Users/ian/projects/nvironment/nvironment-api/node_modules/@ianwremmel/koolaid/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import {default as access} from './decorators/access';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ian/projects/nvironment/nvironment-api/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.cls_wrapMethod [as _load] (/Users/ian/projects/nvironment/nvironment-api/node_modules/newrelic/lib/shimmer.js:230:38)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ian/projects/nvironment/nvironment-api/src/server.js:4:29)
```

**Comment by ianwremmel** [comment]
Still not fixed

**Comment by ianwremmel** [comment]
This is fixed
